version: 0.0
os: linux
files:
  - source: /
    destination: /blog-api
  - source: nginx.conf
    destination: /etc/nginx
hooks:
  BeforeInstall:
    - location: deploy/pre-install.sh
      timeout: 3600
  AfterInstall:
    - location: deploy/post-install.sh
      timeout: 180
  ApplicationStart:
    - location: deploy/start-application.sh
      timeout: 180
  ApplicationStop:
    - location: deploy/stop-application.sh
      timeout: 180